-- ============================================================
-- init/01_create_tables.sql
-- This script runs automatically when the Oracle XE container
-- starts for the first time via docker-compose.
-- It is placed in /container-entrypoint-initdb.d/ and executed
-- by the gvenzl/oracle-xe image's entrypoint as the APP_USER.
-- ============================================================

-- Drop tables if they already exist (safe re-run)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MONTHLY_STATS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TARIFFS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- TARIFFS
CREATE TABLE TARIFFS (
    TARIFF_ID    NUMBER(5)       NOT NULL,
    NAME         VARCHAR2(100)   NOT NULL,
    MONTHLY_FEE  NUMBER(10, 2)   NOT NULL,
    DATA_LIMIT   NUMBER(10)      NOT NULL,
    MINUTE_LIMIT NUMBER(10)      NOT NULL,
    SMS_LIMIT    NUMBER(10)      NOT NULL,
    CONSTRAINT PK_TARIFFS        PRIMARY KEY (TARIFF_ID),
    CONSTRAINT CHK_TARIFFS_FEE   CHECK (MONTHLY_FEE  >= 0),
    CONSTRAINT CHK_TARIFFS_DATA  CHECK (DATA_LIMIT   >= 0),
    CONSTRAINT CHK_TARIFFS_MIN   CHECK (MINUTE_LIMIT >= 0),
    CONSTRAINT CHK_TARIFFS_SMS   CHECK (SMS_LIMIT    >= 0)
);

-- CUSTOMERS
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID  NUMBER(10)      NOT NULL,
    NAME         NVARCHAR2(100)  NOT NULL,
    CITY         NVARCHAR2(100)  NOT NULL,
    SIGNUP_DATE  DATE            NOT NULL,
    TARIFF_ID    NUMBER(5)       NOT NULL,
    CONSTRAINT PK_CUSTOMERS       PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT FK_CUSTOMERS_TARIFF FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS(TARIFF_ID)
);

CREATE INDEX IDX_CUSTOMERS_TARIFF ON CUSTOMERS(TARIFF_ID);
CREATE INDEX IDX_CUSTOMERS_SIGNUP ON CUSTOMERS(SIGNUP_DATE);
CREATE INDEX IDX_CUSTOMERS_CITY   ON CUSTOMERS(CITY);

-- MONTHLY_STATS
CREATE TABLE MONTHLY_STATS (
    ID             NUMBER(10)    NOT NULL,
    CUSTOMER_ID    NUMBER(10)    NOT NULL,
    DATA_USAGE     NUMBER(12, 2) NOT NULL,
    MINUTE_USAGE   NUMBER(10)    NOT NULL,
    SMS_USAGE      NUMBER(10)    NOT NULL,
    PAYMENT_STATUS VARCHAR2(10)  NOT NULL,
    CONSTRAINT PK_MONTHLY_STATS    PRIMARY KEY (ID),
    CONSTRAINT FK_MONTHLY_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT UQ_MONTHLY_CUSTOMER UNIQUE (CUSTOMER_ID),
    CONSTRAINT CHK_DATA_USAGE      CHECK (DATA_USAGE   >= 0),
    CONSTRAINT CHK_MINUTE_USAGE    CHECK (MINUTE_USAGE >= 0),
    CONSTRAINT CHK_SMS_USAGE       CHECK (SMS_USAGE    >= 0),
    CONSTRAINT CHK_PAYMENT_STATUS  CHECK (PAYMENT_STATUS IN ('PAID', 'UNPAID', 'LATE'))
);

CREATE INDEX IDX_MONTHLY_PAYMENT  ON MONTHLY_STATS(PAYMENT_STATUS);
CREATE INDEX IDX_MONTHLY_CUSTOMER ON MONTHLY_STATS(CUSTOMER_ID);
